export class AuthMS {
  static SERVICE_NAME = 'AUTH_SERVICES';
  static FIND_MESSAGE = 'AUTH_FIND';
  static FIND_ONE_BY_EMAIL_MESSAGE = 'AUTH_FIND_ONE_BY_EMAIL_MESSAGE';
  static FIND_ONE_BY_ID_MESSAGE = 'AUTH_FIND_ONE_BY_ID_MESSAGE';
  static CREATE_MESSAGE = 'AUTH_CREATE_MESSAGE';
  static LOGIN_WITH_PASSWORD = 'AUTH_LOGIN_WITH_PASSWORD';
  static REFRESH_TOKENS = 'AUTH_REFRESH_TOKENS';
  static VALIDATE_TOKEN = 'AUTH_VALIDATE_TOKEN';
  private constructor() {}
}
